server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhangzimuzjq/aisptingcloud.git
          searchPaths: config # 检索路径
          username: 1278144124@qq.com   # github账号
          password: zjqdds2017
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
