server:
  port: 8090
spring:
  application:
    name: zipkinclient
  sleuth:
    web:
      client:
        enabled: true   # 启用请求追踪
    sampler:
      probability: 1.0  # 采样比例 默认1.0
  zipkin:
    base-url: http://localhost:9090/  # zipkin server 地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
